name: historias
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  firebase_auth: ^0.8.4+2
  cloud_firestore: ^0.9.13+1
  google_sign_in: ^4.0.1+3
  shared_preferences: ^0.5.2
  fluttertoast: ^3.0.4
  firebase_storage: ^2.1.1+2
  image_picker: ^0.6.0+2
  cached_network_image: ^0.8.0
  intl: ^0.15.8
  firebase_database: ^2.0.3
  flutter_bloc: ^0.13.0
  equatable: ^0.2.3
  bloc: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter   
  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/cat/
    - assets/products/
